"""Sessies per apparaat, en rechten die van de tier afwijken

Twee tabellen erbij, geen enkele bestaande kolom aangeraakt.

`user_sessions` maakt inloggen intrekbaar. Een inlogtoken staat nergens en kan dus niet
worden teruggehaald; een vernieuwingstoken staat hier als afdruk, en één rij doorstrepen
gooit precies dat ene apparaat eruit. `previous_hash` is er om diefstal te zien: komt een
al vervangen token alsnog langs, dan bestaat er een kopie en gaat de sessie dicht.

`user_permissions` maakt een greep uit de rechten mogelijk. Een tier is een rechte lijn —
tier 2 mag alles wat tier 3 mag, plus meer — maar "mag alleen de lampen, de mail en het
weer" is geen stuk van die lijn. Zonder deze tabel zou zo iemand een tier moeten krijgen die
hem meteen ook het uploadschema en de skills laat zien. `granted=False` bestaat ook, voor
iemand die verder alles mag behalve dit ene ding.

Allebei nieuw en leeg, dus er valt niets te vullen en `server_default` is nergens nodig.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "0005_sessions_and_permissions"
down_revision = "0004_skill_engine_and_tasks"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(length=80), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_key', name='uq_user_permission')
    )
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_previous_hash'), 'user_sessions', ['previous_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_hash'), 'user_sessions', ['refresh_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_previous_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    # ### end Alembic commands ###
